---
title: "R Notebook"
output: html_notebook
---
title: "flohmarkt_patti"
author: "Patricia Bauer"
date: "19 5 2020"
output: html_document
---

```{r installieren der Pakete}
library(readr)
library(lubridate)
library(dplyr)
```

```{r lesen der csv Dateien}
umsatz <- read_csv('umsatzdaten_gekuerzt.csv')
wetter <- read_csv('wetter.csv')
```

```{r gefuelteTemp}
#erstellen der Tabelle gefuehlte Temperatur
wetter$gefuehlteTemp <- 0
#0= sehr kalt; 1= kalt; 2=warm; 3= sehr warm
wetter$gefuehlteTemp [wetter$Temperatur < 0] = 0
wetter$gefuehlteTemp [wetter$Temperatur > 0] = 1
wetter$gefuehlteTemp [wetter$Temperatur > 9.999] = 2
wetter$gefuehlteTemp [wetter$Temperatur > 19.999] = 3

#selektieren uns speichern der Tabelle gefuehlte Temperatur
#gefuehlteTemp<- dplyr::filter(wetter, flohmarkt == 1)
gefuehlteTemp <- dplyr::select(wetter, gefuehlteTemp, Datum)
#write.csv2(gefuehlteTemp, "gefuehlte_Temperatur.csv")
write_csv(gefuehlteTemp, "gefuehlte_Temperatur.csv")
```

```{r kiel macht auf}
#erstellen der Tabelle Kielmachtauf
umsatz$Kielmachtauf <- 0
umsatz$Kielmachtauf [umsatz$Datum == "2019-03-03"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2019-04-27"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2019-10-03"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2019-11-02"] = 1

umsatz$Kielmachtauf [umsatz$Datum == "2018-03-04"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2018-04-29"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2018-10-07"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2018-11-04"] = 1

umsatz$Kielmachtauf [umsatz$Datum == "2017-03-05"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2017-05-07"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2017-10-01"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2017-11-05"] = 1

umsatz$Kielmachtauf [umsatz$Datum == "2016-03-06"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2016-10-02"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2016-11-06"] = 1

umsatz$Kielmachtauf [umsatz$Datum == "2015-03-01"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2015-10-03"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2015-11-08"] = 1

umsatz$Kielmachtauf [umsatz$Datum == "2014-03-02"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2014-10-05"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2014-11-02"] = 1

umsatz$Kielmachtauf [umsatz$Datum == "2013-03-03"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2013-10-06"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2013-11-03"] = 1

umsatz$Kielmachtauf [umsatz$Datum == "2016-03-04"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2016-10-07"] = 1
umsatz$Kielmachtauf [umsatz$Datum == "2016-11-04"] = 1

#selektieren uns speichern der Tabelle kielmacht auf
Kielmachtauf<- dplyr::filter(umsatz, Kielmachtauf == 1)
kielmachtauf<- dplyr::select(Kielmachtauf, Kielmachtauf, Datum)

#write.csv2(kielmachtauf, "kielmachtauf.csv")
write_csv(kielmachtauf, "kielmachtauf.csv")
```

```{r flohmarkt}
#erstellen einer neuen Spalte
umsatz$flohmarkt <- 0
umsatz$flohmarkt [umsatz$Datum == "2019-04-07"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-04-28"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-05-05"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-05-26"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-06-02"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-07-07"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-07-14"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-08-04"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-08-25"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-09-01"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-10-06"] = 1
umsatz$flohmarkt [umsatz$Datum == "2019-10-13"] = 1

umsatz$flohmarkt [umsatz$Datum == "2018-04-01"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-04-22"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-05-06"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-05-25"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-06-03"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-07-01"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-07-15"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-08-05"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-09-02"] = 1
umsatz$flohmarkt [umsatz$Datum == "2018-09-30"] = 1

umsatz$flohmarkt [umsatz$Datum == "2017-04-02"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-04-23"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-05-07"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-05-21"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-06-04"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-07-02"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-07-16"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-08-06"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-08-27"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-09-03"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-09-24"] = 1
umsatz$flohmarkt [umsatz$Datum == "2017-10-01"] = 1

umsatz$flohmarkt [umsatz$Datum == "2016-04-03"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-04-24"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-05-01"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-05-22"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-06-05"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-07-02"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-07-17"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-08-07"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-08-28"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-09-04"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-09-25"] = 1
umsatz$flohmarkt [umsatz$Datum == "2016-10-02"] = 1

umsatz$flohmarkt [umsatz$Datum == "2013-04-07"] = 1
umsatz$flohmarkt [umsatz$Datum == "2013-10-06"] = 1

#selektieren uns speichern der Tabelle flohmarkt
flohmarkt<- dplyr::filter(umsatz, flohmarkt == 1)
flohmarkt<- dplyr::select(flohmarkt, flohmarkt, Datum)
#write.csv2(flohmarkt, "flohmarkt.csv")
write_csv(flohmarkt, "flohmarkt.csv")
```

```{r regression}
mod <- lm(Umsatz ~ flohmarkt + Kielmachtauf + as.factor(Warengruppe), umsatz)
summary(mod)
```



