---
title: "flohmarkt_patti"
author: "Patricia Bauer"
date: "19 5 2020"
output: html_document
---

```{r installieren der Pakete}
library(readr)
library(lubridate)
library(dplyr)
```

```{r lesen der csv Dateien}
umsatz <- read_csv('umsatzdaten_gekuerzt.csv')
wetter <- read_csv('wetter.csv')
```
```{r gefuelteTemp}
datum<-wetter$Datum
wetter$jahreszeit <- quarter(datum, with_year = TRUE)
wetter$gefuehlteTemp <- 0
wetter$gefuehlteTemp [wetter$Temperatur < 0] = "sehr kalt"
wetter$gefuehlteTemp [wetter$Temperatur > 0] = "kalt"
wetter$gefuehlteTemp [wetter$Temperatur > 9.999] = "warm"
wetter$gefuehlteTemp [wetter$Temperatur > 19.999] = "sehr warm"
```

```{r kiel macht auf}
umsatz$Kielmachtauf <- NaN
umsatz$Kielmachtauf [umsatz$Datum == "2019-03-03"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2019-04-27"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2019-10-03"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2019-11-02"] = "offen"

umsatz$Kielmachtauf [umsatz$Datum == "2018-03-04"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2018-04-29"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2018-10-07"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2018-11-04"] = "offen"

umsatz$Kielmachtauf [umsatz$Datum == "2017-03-05"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2017-05-07"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2017-10-01"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2017-11-05"] = "offen"

umsatz$Kielmachtauf [umsatz$Datum == "2016-03-06"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2016-10-02"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2016-11-06"] = "offen"

umsatz$Kielmachtauf [umsatz$Datum == "2015-03-01"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2015-10-03"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2015-11-08"] = "offen"

umsatz$Kielmachtauf [umsatz$Datum == "2014-03-02"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2014-10-05"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2014-11-02"] = "offen"

umsatz$Kielmachtauf [umsatz$Datum == "2013-03-03"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2013-10-06"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2013-11-03"] = "offen"

umsatz$Kielmachtauf [umsatz$Datum == "2016-03-04"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2016-10-07"] = "offen"
umsatz$Kielmachtauf [umsatz$Datum == "2016-11-04"] = "offen"
```

```{r flohmarkt}
umsatz$flohmarkt <- NaN
umsatz$flohmarkt [umsatz$Datum == "2019-04-07"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-04-28"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-05-05"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-05-26"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-06-02"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-07-07"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-07-14"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-08-04"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-08-25"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-09-01"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-10-06"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2019-10-13"] = "Flohmarkt"

umsatz$flohmarkt [umsatz$Datum == "2018-04-01"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-04-22"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-05-06"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-05-25"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-06-03"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-07-01"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-07-15"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-08-05"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-09-02"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2018-09-30"] = "Flohmarkt"

umsatz$flohmarkt [umsatz$Datum == "2017-04-02"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-04-23"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-05-07"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-05-21"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-06-04"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-07-02"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-07-16"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-08-06"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-08-27"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-09-03"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-09-24"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2017-10-01"] = "Flohmarkt"

umsatz$flohmarkt [umsatz$Datum == "2016-04-03"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-04-24"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-05-01"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-05-22"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-06-05"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-07-02"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-07-17"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-08-07"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-08-28"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-09-04"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-09-25"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2016-10-02"] = "Flohmarkt"

umsatz$flohmarkt [umsatz$Datum == "2013-04-07"] = "Flohmarkt"
umsatz$flohmarkt [umsatz$Datum == "2013-10-06"] = "Flohmarkt"
```


